# Generated by Django 3.2.11 on 2022-01-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoadImage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image2analysis',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Cargar Imagen: '),
        ),
    ]
