# Generated by Django 3.2.11 on 2022-01-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoadImage', '0002_alter_image_image2analysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThresholdData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upperThres', models.IntegerField(blank=True, null=True, verbose_name='Upper Threshold')),
                ('lowerThres', models.IntegerField(blank=True, null=True, verbose_name='Lower Threshold')),
            ],
        ),
    ]
